import sys
import os
from sqlalchemy import text
from app.core.database import SessionLocal
from app.models import (
    Student, Company, Room, Panel, Shortlist,
    ScheduleVersion, Interview, Disruption, ReplanProposal, Notification
)
from app.services.generator import DatasetGenerator

def seed_database(seed: int = 42):
    """
    Cleanly wipes existing data (cascade delete) and populates
    the database with the deterministic dataset generated by DatasetGenerator.
    """
    db = SessionLocal()
    try:
        print("Clearing existing data from database...")

        # Cascade truncate or delete in reverse foreign-key order
        db.execute(text("TRUNCATE notifications, replan_proposals, interviews, schedule_versions, disruptions, shortlists, panels, rooms, companies, students CASCADE;"))
        db.commit()

        print(f"Generating deterministic dataset with seed={seed}...")
        gen = DatasetGenerator(seed=seed)
        data = gen.generate_all()

        # Insert Students
        print(f"Inserting {len(data['students'])} students...")
        db.bulk_insert_mappings(Student, data["students"])

        # Insert Companies
        print(f"Inserting {len(data['companies'])} companies...")
        db.bulk_insert_mappings(Company, data["companies"])

        # Insert Panels
        print(f"Inserting {len(data['panels'])} panels...")
        db.bulk_insert_mappings(Panel, data["panels"])

        # Insert Rooms
        print(f"Inserting {len(data['rooms'])} rooms...")
        db.bulk_insert_mappings(Room, data["rooms"])

        # Insert Shortlists
        print(f"Inserting {len(data['shortlists'])} shortlists...")
        db.bulk_insert_mappings(Shortlist, data["shortlists"])

        db.commit()
        print("Database seed completed successfully!")

        # Verification print
        student_count = db.query(Student).count()
        company_count = db.query(Company).count()
        room_count = db.query(Room).count()
        panel_count = db.query(Panel).count()
        shortlist_count = db.query(Shortlist).count()

        print("================ SEED VERIFICATION SUMMARY ================")
        print(f"Students   : {student_count} (Expected: 800)")
        print(f"Companies  : {company_count} (Expected: 35)")
        print(f"Rooms      : {room_count} (Expected: 20)")
        print(f"Panels     : {panel_count}")
        print(f"Shortlists : {shortlist_count}")
        print("==========================================================")

    except Exception as e:
        db.rollback()
        print(f"Error seeding database: {e}")
        raise e
    finally:
        db.close()

if __name__ == "__main__":
    seed_database()
