"""create_initial_10_tables

Revision ID: 96b2729a56b8
Revises: 
Create Date: 2026-08-24 09:30:51.594603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '96b2729a56b8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('cgpa_cutoff', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('priority_tier', sa.Integer(), nullable=False),
    sa.Column('panel_count', sa.Integer(), nullable=False),
    sa.Column('interview_duration_mins', sa.Integer(), nullable=False),
    sa.Column('day_availability_mask', sa.Integer(), server_default='15', nullable=False),
    sa.Column('arrival_delay_mins', sa.Integer(), server_default='0', nullable=False),
    sa.CheckConstraint('cgpa_cutoff >= 0.00 AND cgpa_cutoff <= 10.00', name='chk_company_cgpa_cutoff'),
    sa.CheckConstraint('panel_count >= 1 AND panel_count <= 10', name='chk_company_panel_count'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('disruptions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('disruption_type', sa.String(length=30), nullable=False),
    sa.Column('target_entity_type', sa.String(length=20), nullable=False),
    sa.Column('target_entity_id', sa.UUID(), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('injected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rooms',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('building', sa.String(length=50), nullable=False),
    sa.Column('room_number', sa.String(length=20), nullable=False),
    sa.Column('capacity', sa.Integer(), server_default='6', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_number')
    )
    op.create_table('students',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('roll_number', sa.String(length=20), nullable=False),
    sa.Column('cgpa', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('branch', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='ELIGIBLE', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('cgpa >= 0.00 AND cgpa <= 10.00', name='chk_student_cgpa'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('roll_number')
    )
    op.create_table('panels',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('panel_name', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule_versions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.Column('disruption_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['disruption_id'], ['disruptions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shortlists',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('priority_rank', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'student_id', name='uq_shortlists_company_student')
    )
    op.create_index('idx_shortlists_company_student', 'shortlists', ['company_id', 'student_id'], unique=False)
    op.create_table('interviews',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('shortlist_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('panel_id', sa.UUID(), nullable=True),
    sa.Column('room_id', sa.UUID(), nullable=True),
    sa.Column('day', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('conflict_reason', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['panel_id'], ['panels.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['shortlist_id'], ['shortlists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['schedule_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_interviews_panel_slot', 'interviews', ['version_id', 'panel_id', 'day', 'start_time', 'end_time'], unique=False, postgresql_where=sa.text("status = 'SCHEDULED'"))
    op.create_index('idx_interviews_room_slot', 'interviews', ['version_id', 'room_id', 'day', 'start_time', 'end_time'], unique=False, postgresql_where=sa.text("status = 'SCHEDULED'"))
    op.create_index('idx_interviews_student_slot', 'interviews', ['version_id', 'student_id', 'day', 'start_time', 'end_time'], unique=False, postgresql_where=sa.text("status = 'SCHEDULED'"))
    op.create_index('idx_interviews_version_lookup', 'interviews', ['version_id', 'status'], unique=False)
    op.create_table('replan_proposals',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('disruption_id', sa.UUID(), nullable=False),
    sa.Column('base_version_id', sa.UUID(), nullable=False),
    sa.Column('proposed_version_id', sa.UUID(), nullable=False),
    sa.Column('diff_matrix', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metrics_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='PROPOSED', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['base_version_id'], ['schedule_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['disruption_id'], ['disruptions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proposed_version_id'], ['schedule_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('replan_proposal_id', sa.UUID(), nullable=False),
    sa.Column('recipient_type', sa.String(length=20), nullable=False),
    sa.Column('recipient_id', sa.UUID(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['replan_proposal_id'], ['replan_proposals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifications')
    op.drop_table('replan_proposals')
    op.drop_index('idx_interviews_version_lookup', table_name='interviews')
    op.drop_index('idx_interviews_student_slot', table_name='interviews', postgresql_where=sa.text("status = 'SCHEDULED'"))
    op.drop_index('idx_interviews_room_slot', table_name='interviews', postgresql_where=sa.text("status = 'SCHEDULED'"))
    op.drop_index('idx_interviews_panel_slot', table_name='interviews', postgresql_where=sa.text("status = 'SCHEDULED'"))
    op.drop_table('interviews')
    op.drop_index('idx_shortlists_company_student', table_name='shortlists')
    op.drop_table('shortlists')
    op.drop_table('schedule_versions')
    op.drop_table('panels')
    op.drop_table('students')
    op.drop_table('rooms')
    op.drop_table('disruptions')
    op.drop_table('companies')
    # ### end Alembic commands ###
